#### general settings
name: RCAN_branch3
use_tb_logger: true
model: sr
distortion: sr
scale: 4
gpu_ids: [0]

#### network structures
network_G:
  which_model_G: RCAN
  n_resblocks: 20 #number of residual blocks
  n_feats: 50 #number of feature maps
  n_resgroups: 10
  res_scale: 1 #residual scaling
  n_colors: 3
  rgb_range: 255
  scale: 4
  reduction: 16

#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT_rcan
    dataroot_GT: dataset/DIV2K_scale_sub_psnr_GT_class2
    dataroot_LQ: dataset/DIV2K_scale_sub_psnr_LR_class2
    # dataroot_GT: dataset/DIV2K_scale_sub/GT
    # dataroot_LQ: dataset/DIV2K_scale_sub/LR

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 4
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set5
    mode: LQGT_rcan
    dataroot_GT: dataset/Set5_valid_sub/GT
    dataroot_LQ: dataset/Set5_valid_sub/LR
    # dataroot_GT: dataset/DIV2K_valid_sub/GT
    # dataroot_LQ: dataset/DIV2K_valid_sub/LR

#### path
path:
  pretrain_model_G: dataset/resume.pth
  strict_load: true
  resume_state: dataset/resume.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  T_period: [500000]
  restarts: [500000]
  restart_weights: [1]
  eta_min: !!float 1e-7
  lr_gamma: 0.5
  clear_state: 1000000

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: 5000

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: 5000
