#### general settings
name: ClassSR_RCAN_finetone
use_tb_logger: true
model: ClassSR
distortion: sr
scale: 4
gpu_ids: [1]
patch_size: 32
step: 28
fix_SR_module: false



#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT_rcan
    # dataroot_GT: /data0/xtkong/data/DIV2K_scale_sub/GT
    # dataroot_LQ: /data0/xtkong/data/DIV2K_scale_sub/LR
    dataroot_GT: dataset/DIV2K_scale_sub/GT
    dataroot_LQ: dataset/DIV2K_scale_sub/LR

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 60
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K10
    mode: LQGT_rcan
    dataroot_GT: dataset/val_10/HR
    dataroot_LQ: dataset/val_10/LR
    # dataroot_GT: dataset/DIV2k_valid_sub/GT
    # dataroot_LQ: dataset/DIV2k_valid_sub/LR

#### network structures
network_G:
  which_model_G: classSR_3class_rcan
  in_nc: 3
  out_nc: 3

#### path
path:
  #pretrain_model_G: dataset/46000_G.pth
  pretrain_model_G : experiments/ClassSR_RCAN/models/62000_G.pth
  pretrain_model_classifier: ~
  pretrain_model_G_branch1: ~
  pretrain_model_G_branch2: ~
  pretrain_model_G_branch3: ~
  #pretrain_model_G_branch1: dataset/500000_G.pth
  #pretrain_model_G_branch2: dataset/500000_G2.pth
  #pretrain_model_G_branch3: dataset/500000_G3.pth
  # pretrain_model_G_branch1: dataset/RCAN_branch1.pdparams
  # pretrain_model_G_branch2: dataset/RCAN_branch2.pdparams
  # pretrain_model_G_branch3: dataset/RCAN_branch3.pdparams
  #resume_state: dataset/46000.state
  resume_state: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 200000
  warmup_iter: -1  # no warm up
  T_period: [500000, 20000]
  restarts: [500000]
  restart_weights: [0.5]
  eta_min: !!float 2e-5

  pixel_criterion: ClassSR_loss
  # l1w: 250
  # class_loss_w: 0.5
  # average_loss_w: 3
  l1w: 4
  class_loss_w: 2
  average_loss_w: 6

  manual_seed: 10
  val_freq: !!float 1000

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2000
